apiVersion: v1
kind: ConfigMap
metadata:
  name: ${name}
  namespace: ${namespace}
data:
  data.txt: |
    Helm managed template, you can leverage terragrunt/terraform functions here, but can't add other things to kustomize.yaml.
