apiVersion: v1
kind: Secret
metadata:
  name: ${name}
  namespace: ${namespace}
data:
  LDAP_ADMIN_PASSWORD: ${base64encode(ldap_admin_password)}
  LDAP_CONFIG_PASSWORD: ${base64encode(ldap_config_password)}
type: Opaque
