apiVersion: v1
kind: Secret
metadata:
  name: ${name}
  namespace: ${namespace}
data:
  admin-password: ${base64encode(admin_pass)}
  management-password: ${base64encode(management_pass)}
  postgresql-password: ${base64encode(postgres_pass)}
  postgresql-postgres-password: ${base64encode(postgres_pass)}
type: Opaque
